# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS deps

WORKDIR /workspace

COPY package*.json ./
COPY apps/backend/package.json apps/backend/package.json
COPY apps/web/package.json apps/web/package.json

RUN --mount=type=cache,target=/root/.npm \
    npm install

#########################################################

FROM deps AS builder

WORKDIR /workspace

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build -w nextjs_tailwind_shadcn_ts

#########################################################

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /workspace/apps/web/.next/standalone ./
COPY --from=builder /workspace/apps/web/.next/static ./.next/static
COPY --from=builder /workspace/apps/web/public ./public

EXPOSE 3001

CMD ["node","server.js"]
