services:
  backend:
    image: ghcr.io/kiseki1111/zafi-backend:latest
    container_name: iqbal-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:secret_password@172.17.0.1:5432/rbac_api_db?schema=public}
      PORT: 3030
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      WAHA_API_URL: ${WAHA_API_URL:-https://waha.zafii.tech}
      WAHA_API_KEY: ${WAHA_API_KEY:-ZafitechDunia12345#}
      WHATSAPP_API_KEY: ${WHATSAPP_API_KEY:-ZafitechDunia12345#}
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "3030:3030"
    networks:
      app-network:
        aliases:
          - backend

  web:
    image: ghcr.io/kiseki1111/zafi-web:latest
    container_name: iqbal-web
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      PORT: 3001
      HOSTNAME: "0.0.0.0"
      BACKEND_URL: http://backend:3030
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    name: coolify-network
    external: true
