# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS deps

WORKDIR /workspace

COPY package*.json ./
COPY apps/backend/package.json apps/backend/package.json
COPY apps/web/package.json apps/web/package.json

RUN --mount=type=cache,target=/root/.npm \
    npm ci

#########################################################

FROM deps AS builder

WORKDIR /workspace

COPY . .

RUN npm run prisma:generate -w rbac-service
RUN npm run build -w rbac-service

#########################################################

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
RUN apk add --no-cache openssl

# Salin berkas manifes workspaces
COPY package*.json ./
COPY apps/backend/package.json apps/backend/package.json
COPY apps/web/package.json apps/web/package.json

# 1. Instal dependensi khusus produksi
RUN --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

# 2. Salin folder skema Prisma dari stage builder
COPY --from=builder /workspace/apps/backend/src/infrastructure/prisma ./src/infrastructure/prisma

# 3. PERBAIKAN UTAMA: Generate ulang Prisma Client di dalam lingkungan runner produksi
RUN npx prisma generate --schema=src/infrastructure/prisma/schema.prisma

# COPY --from=builder /workspace/apps/backend/package.json .

# RUN npm install --omit=dev

COPY --from=builder /workspace/apps/backend/dist ./dist
COPY --from=builder /workspace/apps/backend/public ./public
# COPY --from=builder /workspace/apps/backend/src/infrastructure/prisma ./src/infrastructure/prisma

EXPOSE 3030

CMD ["node","dist/src/main.js"]
