# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS deps

WORKDIR /app

COPY package*.json ./

COPY apps/web/package.json ./apps/web/package.json

RUN --mount=type=cache,target=/root/.npm \
    npm install

########################

FROM node:22-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

WORKDIR /app/apps/web

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

########################

FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/apps/web/.next/standalone ./

COPY --from=builder /app/apps/web/.next/static ./.next/static

COPY --from=builder /app/apps/web/public ./public

EXPOSE 3001

CMD ["node","server.js"]
