# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS deps

WORKDIR /workspace

ENV NODE_ENV=development

COPY package*.json ./
COPY apps/backend/package.json apps/backend/package.json
COPY apps/web/package.json apps/web/package.json

RUN --mount=type=cache,target=/root/.npm \
    rm -f package-lock.json && npm install --include=dev --legacy-peer-deps

#########################################################

FROM deps AS builder

WORKDIR /workspace

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV BACKEND_URL=http://backend:3030
ENV NEXT_PRIVATE_STANDALONE=1

COPY . .

RUN npm run build -w nextjs_tailwind_shadcn_ts

#########################################################

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3001

# 1. Salin seluruh arsitektur standalone monorepo hasil build Next.js
COPY --from=builder /workspace/apps/web/.next/standalone ./

# 2. Salin aset statis ke folder sub-app agar styling css tidak hilang
COPY --from=builder /workspace/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder /workspace/apps/web/public ./apps/web/public

EXPOSE 3001

CMD ["node", "apps/web/server.js"]
