services:
  backend:
    image: ghcr.io/sisfoku/iqbal-backend:${IMAGE_TAG:-latest}
    container_name: iqbal-backend
    env_file:
      - ./apps/backend/.env
    restart: unless-stopped

    ports:
      - "3030:3030"

    networks:
      - backend

  web:
    image: ghcr.io/sisfoku/iqbal-web:${IMAGE_TAG:-latest}
    container_name: iqbal-web
    restart: unless-stopped

    depends_on:
      - backend

    environment:
      BACKEND_URL: http://backend:3030

    ports:
      - "3001:3001"

    networks:
      - backend

networks:
  backend:
    external: true





# version: "3.9"

# services:
#   backend:
#     image: ghcr.io/sisfoku/iqbal-backend:latest
#     container_name: iqbal-backend
#     restart: unless-stopped
#     env_file:
#       - ./apps/backend/.env

#     ports:
#       - "3030:3030"

#     healthcheck:
#       test: ["CMD","wget","--spider","http://localhost:3030"]
#       interval: 30s
#       timeout: 5s
#       retries: 5
#       start_period: 30s

#     networks:
#       - backend

#   web:
#     image: ghcr.io/sisfoku/iqbal-web:latest
#     container_name: iqbal-web
#     restart: unless-stopped
#     depends_on:
#       backend:
#         condition: service_healthy

#     environment:
#       NODE_ENV: production
#       BACKEND_URL: http://backend:3030

#     ports:
#       - "3001:3001"

#     networks:
#       - backend

# networks:
#   backend:
#     external: true




# services:
#   app:
#     image: ghcr.io/sisfoku/iqbal-backend:latest
#     container_name: zafi-app-service
#     restart: unless-stopped

#     env_file:
#       - apps/backend/.env

#     ports:
#       - "3030:3030"

#     networks:
#       - backend

#   web:
#     image: ghcr.io/sisfoku/iqbal-web:latest
#     container_name: zafi-web-service
#     restart: unless-stopped
#     ports:
#       - "3001:3001"
#     environment:
#       - BACKEND_URL=http://app:3030
#     networks:
#       - backend

#   rbac-db:
#     image: pgvector/pgvector:pg15
#     container_name: rbac-service-postgres
#     restart: always

#     environment:
#       POSTGRES_USER: ${DATABASE_USER:-postgres}
#       POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secret_password}
#       POSTGRES_DB: ${DATABASE_NAME:-rbac_api_db}

#     ports:
#       - "127.0.0.1:5432:5432"

#     volumes:
#       - rbac_postgres_data:/var/lib/postgresql/data
    
#     networks:
#       - backend

# volumes:
#   rbac_postgres_data:
#     driver: local

# networks:
#   backend:
#     external: true
