# syntax=docker/dockerfile:1.7

############################
# Dependencies
############################
FROM node:22-alpine AS deps

WORKDIR /app
COPY package*.json ./

COPY apps/backend/package.json ./apps/backend/package.json

RUN --mount=type=cache,target=/root/.npm \
    npm install

############################
# Builder
############################
FROM node:22-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

WORKDIR /app/apps/backend

RUN npx prisma generate \
    --schema=src/infrastructure/prisma/schema.prisma

RUN npm run build

############################
# Production
############################
FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./

COPY apps/backend/package.json ./apps/backend/package.json

RUN --mount=type=cache,target=/root/.npm \
    npm install --omit=dev

WORKDIR /app/apps/backend

COPY --from=builder /app/apps/backend/dist ./dist
COPY --from=builder /app/apps/backend/public ./public
COPY --from=builder /app/apps/backend/src/infrastructure/prisma ./src/infrastructure/prisma
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3030

CMD ["node","dist/main.js"]
